### ISSUE TITLE
Remove timer from finger tapping task as the subjects use the timer to sync their tapping.

### ISSUE THREAD

**Issue by CalebUAz** [ml4ai/tomcat-baseline-tasks#61]

**Comment by eduongAZ** [comment]
Chinmai reported that the participants relied on the timer to synchronize their taps instead of establishing their own tapping rhythm. We should consider hiding the timer from the participants to ensure that they rely on each other for timing their taps. We should still leave the 10 seconds practice session timer on during then, but hide it during the actual sessions.

To emphasize: we don't remove the timer, we HIDE the timer completely.

**Comment by CalebUAz** [comment]
#59
